package se.ade.mc.skyblock.generator.overworld.biomes

import org.bukkit.block.Biome

internal val supportedBiomes = listOf(
    Biome.OCEAN,
    Biome.PLAINS,
    Biome.DESERT,
    Biome.WINDSWEPT_HILLS,
    Biome.FOREST,
    Biome.TAIGA,
    Biome.SWAMP,
    Biome.MANGROVE_SWAMP,
    Biome.RIVER,
    Biome.FROZEN_OCEAN,
    Biome.FROZEN_RIVER,
    Biome.SNOWY_PLAINS,
    Biome.MUSHROOM_FIELDS,
    Biome.BEACH,
    Biome.JUNGLE,
    Biome.SPARSE_JUNGLE,
    Biome.DEEP_OCEAN,
    Biome.STONY_SHORE,
    Biome.SNOWY_BEACH,
    Biome.BIRCH_FOREST,
    Biome.DARK_FOREST,
    Biome.SNOWY_TAIGA,
    Biome.OLD_GROWTH_PINE_TAIGA,
    Biome.WINDSWEPT_FOREST,
    Biome.SAVANNA,
    Biome.SAVANNA_PLATEAU,
    Biome.BADLANDS,
    Biome.WOODED_BADLANDS,
    Biome.WARM_OCEAN,
    Biome.LUKEWARM_OCEAN,
    Biome.COLD_OCEAN,
    Biome.DEEP_LUKEWARM_OCEAN,
    Biome.DEEP_COLD_OCEAN,
    Biome.DEEP_FROZEN_OCEAN,
    Biome.SUNFLOWER_PLAINS,
    Biome.WINDSWEPT_GRAVELLY_HILLS,
    Biome.FLOWER_FOREST,
    Biome.ICE_SPIKES,
    Biome.OLD_GROWTH_BIRCH_FOREST,
    Biome.OLD_GROWTH_SPRUCE_TAIGA,
    Biome.WINDSWEPT_SAVANNA,
    Biome.ERODED_BADLANDS,
    Biome.BAMBOO_JUNGLE,
    Biome.MEADOW,
    Biome.GROVE,
    Biome.SNOWY_SLOPES,
    Biome.FROZEN_PEAKS,
    Biome.JAGGED_PEAKS,
    Biome.STONY_PEAKS,
    Biome.CHERRY_GROVE,
)